volumes:
    volume_todo:

networks:
    rede_todo:

services:
    container_postgres:
        container_name: container_postgres
        image: postgres:13.16
        environment:
            - POSTGRES_USER=${USUARIO}
            - POSTGRES_PASSWORD=${SENHA}
            - POSTGRES_DB=${BANCO}
        ports:
            - 5432:5432
        volumes:
            - volume_todo:/var/lib/postgresql/data
        networks:
            - rede_todo

    container_backend:
        container_name: container_backend
        build:
            context: .
        ports:
            - 8080:8080
        environment: #Sobrescrevemos as variaveis do aplication.properties
            - spring.datasource.url=jdbc:postgresql://container_postgres:5432/${BANCO}
            - spring.datasource.username=${USUARIO}
            - spring.datasource.password=${SENHA}
        networks:
            - rede_todo
        depends_on:
            - container_postgres